"""initial_schema

Revision ID: 57b1d7b43c06
Revises: 
Create Date: 2026-03-24 14:46:01.408233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b1d7b43c06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mc_number', sa.String(length=50), nullable=True),
    sa.Column('dot_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mc_number', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_company_id'), 'brokers', ['company_id'], unique=False)
    op.create_table('company_default_deductions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('per_load', 'weekly', 'monthly', name='deduction_frequency_enum', create_constraint=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_default_deductions_company_id'), 'company_default_deductions', ['company_id'], unique=False)
    op.create_table('documents',
    sa.Column('entity_type', sa.Enum('load', 'driver', 'truck', 'trailer', name='entity_type_enum', create_constraint=True), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('rate_confirmation', 'pod_bol', 'cdl', 'medical_card', 'bank_info', 'dot_inspection', 'insurance', 'other', name='document_type_enum', create_constraint=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('gcs_object_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_table('drivers',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('company_w2', 'owner_operator_1099', 'lease_operator', name='employment_type_enum', create_constraint=True), nullable=False),
    sa.Column('cdl_number', sa.String(length=50), nullable=True),
    sa.Column('cdl_class', sa.String(length=10), nullable=True),
    sa.Column('cdl_expiry_date', sa.Date(), nullable=True),
    sa.Column('medical_card_expiry_date', sa.Date(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('pay_rate_type', sa.Enum('cpm', 'percentage', 'fixed_per_load', 'hourly', 'salary', name='pay_rate_type_enum', create_constraint=True), nullable=True),
    sa.Column('pay_rate_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('use_company_defaults', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_routing_number', sa.String(length=50), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('available', 'on_route', 'off_duty', 'on_leave', 'terminated', name='driver_status_enum', create_constraint=True), server_default='available', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_company_id'), 'drivers', ['company_id'], unique=False)
    op.create_table('trailers',
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('trailer_type', sa.Enum('dry_van', 'reefer', 'flatbed', 'step_deck', 'tanker', name='trailer_type_enum', create_constraint=True), nullable=True),
    sa.Column('ownership_type', sa.Enum('owned', 'financed', 'leased', 'rented', name='ownership_type_enum', create_constraint=True), nullable=True),
    sa.Column('dot_inspection_date', sa.Date(), nullable=True),
    sa.Column('dot_inspection_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', name='equipment_status_enum', create_constraint=True), server_default='available', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailers_company_id'), 'trailers', ['company_id'], unique=False)
    op.create_table('trucks',
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('ownership_type', sa.Enum('owned', 'financed', 'leased', 'rented', name='ownership_type_enum', create_constraint=True), nullable=True),
    sa.Column('dot_inspection_date', sa.Date(), nullable=True),
    sa.Column('dot_inspection_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', name='equipment_status_enum', create_constraint=True), server_default='available', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_company_id'), 'trucks', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'company_admin', 'dispatcher', 'accountant', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_table('driver_settlements',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('settlement_number', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_accessorials', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'paid', name='settlement_status_enum', create_constraint=True), server_default='draft', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_settlements_company_id'), 'driver_settlements', ['company_id'], unique=False)
    op.create_table('loads',
    sa.Column('load_number', sa.String(length=50), nullable=False),
    sa.Column('broker_load_id', sa.String(length=100), nullable=True),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('truck_id', sa.UUID(), nullable=True),
    sa.Column('trailer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'dispatched', 'at_pickup', 'in_transit', 'delivered', 'delayed', 'billed', 'paid', 'cancelled', name='load_status_enum', create_constraint=True), server_default='planned', nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_miles', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contact_agent', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loads_company_id'), 'loads', ['company_id'], unique=False)
    op.create_table('load_accessorials',
    sa.Column('load_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('fuel_surcharge', 'detention', 'layover', 'lumper', 'stop_off', 'tarp', 'other', name='accessorial_type_enum', create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_accessorials_company_id'), 'load_accessorials', ['company_id'], unique=False)
    op.create_table('load_stops',
    sa.Column('load_id', sa.UUID(), nullable=False),
    sa.Column('stop_type', sa.Enum('pickup', 'delivery', name='stop_type_enum', create_constraint=True), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_stops_company_id'), 'load_stops', ['company_id'], unique=False)
    op.create_table('settlement_line_items',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('load_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('load_pay', 'accessorial', 'deduction', name='settlement_line_type_enum', create_constraint=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['driver_settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_line_items_company_id'), 'settlement_line_items', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_line_items_company_id'), table_name='settlement_line_items')
    op.drop_table('settlement_line_items')
    op.drop_index(op.f('ix_load_stops_company_id'), table_name='load_stops')
    op.drop_table('load_stops')
    op.drop_index(op.f('ix_load_accessorials_company_id'), table_name='load_accessorials')
    op.drop_table('load_accessorials')
    op.drop_index(op.f('ix_loads_company_id'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_driver_settlements_company_id'), table_name='driver_settlements')
    op.drop_table('driver_settlements')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trucks_company_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_trailers_company_id'), table_name='trailers')
    op.drop_table('trailers')
    op.drop_index(op.f('ix_drivers_company_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_company_default_deductions_company_id'), table_name='company_default_deductions')
    op.drop_table('company_default_deductions')
    op.drop_index(op.f('ix_brokers_company_id'), table_name='brokers')
    op.drop_table('brokers')
    op.drop_table('companies')
    # ### end Alembic commands ###
